/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConnectionBD;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.Tabela;

/**
 *
 * @author reubber
 */
public class TelaPendecias extends javax.swing.JFrame {

    /**
     * Creates new form TelaPendecias
     */
    public TelaPendecias() {
        initComponents();
        preencherTabelas("SELECT *FROM atividades order by nome_atv");
        configTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSituacao = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDadosAtividade = new javax.swing.JTable();
        jButtonAprovar = new javax.swing.JButton();
        jButtonRecusar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSituacao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSituacao.setText("Verificando..");
        getContentPane().add(jLabelSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        jTableDadosAtividade.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTableDadosAtividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDadosAtividade.setGridColor(new java.awt.Color(255, 255, 255));
        jTableDadosAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosAtividadeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDadosAtividade);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 930, -1));

        jButtonAprovar.setText("Aprovar");
        getContentPane().add(jButtonAprovar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jButtonRecusar.setText("Reporvar");
        getContentPane().add(jButtonRecusar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoutMin.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencherTabelas(String sql){
        
        ConnectionBD conexao = new ConnectionBD();
       
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Atividade","Solicitante","Curso","Descrição","Categoria","situacao"};
        conexao.getConexao();
        conexao.executaSql(sql);
       
        try
        {
          conexao.rs.first();
            do{
            dados.add(new Object[]{conexao.rs.getInt("cod_atv"),conexao.rs.getString("nome_atv"),conexao.rs.getString("matricula"),conexao.rs.getString("curso"),conexao.rs.getString("descricao"),conexao.rs.getString("categ_atv"),conexao.rs.getString("situacao")});
            
            }while(conexao.rs.next());
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList"+ex);
        }
        
        Tabela modelo = new Tabela(dados,colunas);
        getjTableDadosAtividade().setModel(modelo);
        configTabela();
    
        conexao.closeConnection();
}
    
    public void configTabela(){
        
        getjTableDadosAtividade().getColumnModel().getColumn(0).setPreferredWidth(30); 
        getjTableDadosAtividade().getColumnModel().getColumn(0).setResizable(false);
        getjTableDadosAtividade().getColumnModel().getColumn(1).setPreferredWidth(250);  
        getjTableDadosAtividade().getColumnModel().getColumn(1).setResizable(false);
        getjTableDadosAtividade().getColumnModel().getColumn(2).setPreferredWidth(85); 
        getjTableDadosAtividade().getColumnModel().getColumn(2).setResizable(false);
        getjTableDadosAtividade().getColumnModel().getColumn(3).setPreferredWidth(170);  
        getjTableDadosAtividade().getColumnModel().getColumn(3).setResizable(true);
        getjTableDadosAtividade().getColumnModel().getColumn(4).setPreferredWidth(200);  
        getjTableDadosAtividade().getColumnModel().getColumn(4).setResizable(true);
        getjTableDadosAtividade().getColumnModel().getColumn(5).setPreferredWidth(70);  
        getjTableDadosAtividade().getColumnModel().getColumn(5).setResizable(true);
        getjTableDadosAtividade().getColumnModel().getColumn(6).setPreferredWidth(140);  
        getjTableDadosAtividade().getColumnModel().getColumn(6).setResizable(true);
  
        getjTableDadosAtividade().getTableHeader().setReorderingAllowed(false);             //cmd onde desabilita a reodernar o cabeçalho
        getjTableDadosAtividade().setAutoResizeMode(getjTableDadosAtividade().AUTO_RESIZE_OFF);  //cmd onde usuario nao vai poder redimencionar essa tabela
        getjTableDadosAtividade().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);    //cmd onde ao clicar num campo na tabela so vai poder selecionar um por vez.
    
    
    
    
}
    
    
    
    
    private void jTableDadosAtividadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosAtividadeMouseClicked
        
        ConnectionBD conexao = new ConnectionBD();
        //String nome_situation = ""+getjTableDadosAtividade().getValueAt(getjTableDadosAtividade().getSelectedRow(),6);
        conexao.getConexao();
        conexao.executaSql("SELECT *FROM atividades where situacao = 'pendente'");
        
        try {

            conexao.rs.first();
            
            getjLabelSituacao().setText(conexao.rs.getString("situacao"));
           if(getjLabelSituacao().getText().equals("pendente")){
             getjLabelSituacao().setForeground(Color.orange);
            }else {
                getjLabelSituacao().setForeground(Color.blue);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erro ao selecionar dados."+ex);
        }              
    }//GEN-LAST:event_jTableDadosAtividadeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
     
     dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPendecias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPendecias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPendecias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPendecias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPendecias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAprovar;
    private javax.swing.JButton jButtonRecusar;
    private javax.swing.JLabel jLabelSituacao;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDadosAtividade;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTableDadosAtividade
     */
    public javax.swing.JTable getjTableDadosAtividade() {
        return jTableDadosAtividade;
    }

    /**
     * @param jTableDadosAtividade the jTableDadosAtividade to set
     */
    public void setjTableDadosAtividade(javax.swing.JTable jTableDadosAtividade) {
        this.jTableDadosAtividade = jTableDadosAtividade;
    }

    /**
     * @return the jLabelSituacao
     */
    public javax.swing.JLabel getjLabelSituacao() {
        return jLabelSituacao;
    }
}
